feat: updated cypress, e2ee rework, tests
CaritasDeutschland/caritas-onlineBeratung-frontend pull request #54
Opened 2022-10-24 07:56 UTC by web-mi

Fixes #

## Proposed Changes

  -
  -
  -

2022-10-24 10:47 UTC, MelanieJakobArbeit commented on src/components/app/PreConditions.tsx
> +							type: BUTTON_TYPES.PRIMARY
Texte Übersetzbar machen.

2022-10-24 10:47 UTC, MelanieJakobArbeit commented on src/resources/scripts/i18n/de/e2ee.ts
> +		'Bitte warten Sie bis die Verschlüsselung abgeschlossen ist!'
Wieso has du nicht den gleichen Aufbau der Dateien genutzt wie bei den anderen Sprach Dateien?
roomNotFound: {
notive: {
line3: '',
link: '',
}
}

2022-10-24 10:47 UTC, MelanieJakobArbeit commented on src/resources/scripts/i18n/de/e2eeInformal.ts
> +	'inProgress.copy':
Gleiche Frage wie bei der i18n/de/e2ee.ts

2022-10-24 10:47 UTC, MelanieJakobArbeit commented on src/resources/scripts/i18n/de/overlay.ts
> +	'timeout.confirm': 'Möchten Sie die Seite wirklich verlassen?'
Gleiche wie bei den anderen beiden Dateien.

2022-10-24 10:47 UTC, MelanieJakobArbeit commented on src/resources/scripts/i18n/de/preconditions.ts
> +	'cookie.button': 'Zurück zur vorheringen Seite'
Hier auch wie bei den anderen.

2022-10-24 10:47 UTC, MelanieJakobArbeit commented on src/resources/scripts/i18n/de/preconditionsInformal.ts
> +		'Nachdem Du Cookies in Deinem Browser aktiviert hast, klicke einfach auf die Schaltfläche unten, um zur vorhergehenden Seite zurückzukehren.'
Siehe andere Sprach Dateien.

2022-10-24 10:47 UTC, MelanieJakobArbeit commented on src/resources/scripts/i18n/de/session.ts
>  	'assignSelf.button1.label': 'Antworten',
Siehe andere Sprachdateien.

2022-10-24 10:47 UTC, MelanieJakobArbeit commented on src/resources/scripts/i18n/de/sessionInformal.ts
>  	'assignSelf.overlay.subtitle':
Siehe andere Sprachdateien.

2022-10-24 22:37 UTC, web-mi commented on src/resources/scripts/i18n/de/e2ee.ts
> +		'Bitte warten Sie bis die Verschlüsselung abgeschlossen ist!'
Das geht erst mit der neuen Translation. ;-)

2022-10-25 14:42 UTC, koepferd requested changes

2022-10-25 14:42 UTC, koepferd commented on src/resources/scripts/i18n/de/preconditions.ts
> +	'cookie.button': 'Zurück zur vorheringen Seite'
Please fix Typo: *vorherigen

2022-10-25 14:42 UTC, koepferd commented on src/components/progressbar/Progressbar.tsx
> +import * as React from 'react';
Filename/folder typo: *ProgressBar.tsx

2022-10-28 09:50 UTC, closed without merging